//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Inform7.rc
//
#define IDR_MANIFEST                    1
#define IDR_MAINFRAME                   100
#define IDR_SKEIN                       101
#define IDR_EXTFRAME                    102
#define IDR_ICON                        103
#define IDR_LAUNCHFRAME                 104
#define IDR_BOOKFRAME                   105
#define IDD_ABOUTBOX                    150
#define IDD_SETTINGS                    151
#define IDD_LAUNCHER                    152
#define IDD_SEARCH                      153
#define IDD_NEWPROJECT                  154
#define IDD_SPELLING                    155
#define IDD_PREFS_EDIT                  156
#define IDD_PREFS_TEXT                  157
#define IDD_PREFS_ADVANCED              158
#define IDD_FIND_FILES                  159
#define IDD_FIND                        160
#define IDD_FIND_BASIC                  161
#define IDD_REPLACE                     162
#define ID_FILE_INSTALL_EXT             200
#define ID_FILE_INSTALL_FOLDER          201
#define ID_FILE_INSTALL_XP              202
#define ID_FILE_NEW_EXT                 203
#define ID_FILE_NEW_XP                  204
#define ID_FILE_IMPORT_SKEIN            205
#define ID_FILE_EXPORT_EXT              206
#define ID_EDIT_DELETE                  207
#define ID_EDIT_SPELLING                208
#define ID_EDIT_FIND_NEXT               209
#define ID_EDIT_FIND_PREV               210
#define ID_EDIT_SCROLL                  211
#define ID_EDIT_USE_SEL                 212
#define ID_EDIT_FIND_IN_FILES           213
#define ID_FORMAT_SHIFT_RIGHT           214
#define ID_FORMAT_SHIFT_LEFT            215
#define ID_FORMAT_COMMENT               216
#define ID_FORMAT_UNCOMMENT             217
#define ID_FORMAT_RENUMBER              218
#define ID_PLAY_GO                      220
#define ID_PLAY_STOP                    221
#define ID_PLAY_TEST                    222
#define ID_PLAY_TEST_EXAMPLES           223
#define ID_PLAY_REFRESH                 224
#define ID_PLAY_LOAD                    225
#define ID_PLAY_REPLAY                  226
#define ID_RELEASE_GAME                 240
#define ID_RELEASE_TEST                 241
#define ID_RELEASE_MATERIALS            242
#define ID_RELEASE_IFICTION             243
#define ID_WINDOW_TAB_SOURCE            250
#define ID_WINDOW_TAB_RESULTS           251
#define ID_WINDOW_TAB_STORY             252
#define ID_WINDOW_TAB_TESTING           253
#define ID_WINDOW_TAB_INDEX             254
#define ID_WINDOW_TAB_DOCUMENTATION     255
#define ID_WINDOW_TAB_EXTENSIONS        256
#define ID_WINDOW_TAB_SETTINGS          257
#define ID_WINDOW_SWITCH                258
#define ID_WINDOW_LEFTPANE              260
#define ID_WINDOW_RIGHTPANE             261
#define ID_WINDOW_INDEX_HOME            262
#define ID_WINDOW_INDEX_CONTENTS        263
#define ID_WINDOW_INDEX_ACTIONS         264
#define ID_WINDOW_INDEX_KINDS           265
#define ID_WINDOW_INDEX_PHRASES         266
#define ID_WINDOW_INDEX_RULES           267
#define ID_WINDOW_INDEX_SCENES          268
#define ID_WINDOW_INDEX_WORLD           269
#define ID_HELP_LICENCE                 270
#define ID_HELP_WINDOWS                 271
#define ID_HELP_EXTENSIONS              272
#define ID_HELP_RECIPES                 273
#define ID_APP_PREFS                    274
#define ID_APP_WEBPAGE                  275
#define ID_APP_LAUNCHER                 276
#define ID_HEAD_SHOW                    277
#define ID_HEAD_CURRENT                 278
#define ID_HEAD_INCREASE                279
#define ID_HEAD_REDUCE                  280
#define ID_HEAD_ENTIRE                  281
#define ID_HEAD_PREVIOUS                282
#define ID_HEAD_NEXT                    283
#define ID_FILE_CLEAR_RECENT            284
#define ID_WINDOW_LIST                  300
#define ID_SKEIN_LABEL                  400
#define ID_SKEIN_PLAY                   401
#define ID_SKEIN_EDIT                   402
#define ID_SKEIN_ADD_LABEL              403
#define ID_SKEIN_EDIT_LABEL             404
#define ID_SKEIN_BLESS                  405
#define ID_SKEIN_BLESS_ALL              406
#define ID_SKEIN_INSERT_NEXT            407
#define ID_SKEIN_SPLIT_THREAD           408
#define ID_SKEIN_INSERT_PREVIOUS        409
#define ID_SKEIN_DELETE                 410
#define ID_SKEIN_DELETE_ALL             411
#define ID_SKEIN_TOGGLE_HELP            412
#define ID_SKEIN_SAVE_TRANSCRIPT        413
#define ID_SKEIN_PLAY_ALL               414
#define ID_TRANSCRIPT_BLESS_ALL         415
#define ID_SKEIN_LOCK                   416
#define ID_SKEIN_UNLOCK                 417
#define ID_SKEIN_TRIM                   418
#define ID_SEARCH_SOURCE                450
#define ID_SEARCH_DOCS                  451
#define ID_NAVIGATE_BACK                500
#define ID_NAVIGATE_FORE                501
#define ID_MENU_PROPERTIES              550
#define IDC_CREDITS                     1000
#define IDC_OUTPUT_Z8                   1002
#define IDC_OUTPUT_GLULX                1003
#define IDC_BLORB                       1004
#define IDC_PREDICTABLE                 1005
#define IDC_PROGRESS                    1010
#define IDC_LOGO                        1011
#define IDC_TITLE                       1012
#define IDC_COPYRIGHT                   1013
#define IDC_INTRO                       1014
#define IDC_SEARCH_SOURCE               1015
#define IDC_SEARCH_DOCS                 1016
#define IDC_SEARCH_RESULTS              1017
#define IDC_VERSION                     1018
#define IDC_DIR                         1019
#define IDC_DIRPOPUP                    1020
#define IDC_NAME                        1021
#define IDC_AUTHOR                      1022
#define IDC_TRANSCRIPT_EDIT             1023
#define IDC_DIR_TEXT                    1024
#define IDC_NAME_TEXT                   1025
#define IDC_BADWORD                     1026
#define IDC_SUGGESTIONS                 1027
#define IDC_ADD_DICTIONARY              1028
#define IDC_IGNORE                      1029
#define IDC_REPLACE                     1030
#define IDC_TABSIZE                     1031
#define IDC_CLEANFILES                  1032
#define IDC_CLEANINDEX                  1033
#define IDC_I6DEBUGGING                 1034
#define IDC_LANGUAGE                    1035
#define IDC_GLULX                       1036
#define IDC_TABS_HORIZONTAL             1037
#define IDC_AUTO_INDENT                 1038
#define IDC_AUTO_NUMBER                 1039
#define IDC_FONT                        1040
#define IDC_FONTSIZE                    1041
#define IDC_FIXEDFONT                   1042
#define IDC_ELASTIC_TABS                1043
#define IDC_STORY_BOX                   1044
#define IDC_RANDOM_BOX                  1045
#define IDC_VERSION_BOX                 1046
#define IDC_VERSION_LABEL               1047
#define IDC_VERSION_COMBO               1048
#define IDC_EXAMPLE_LIST                1060
#define IDC_STOP                        1061
#define IDC_COLOUR_SOURCE               1062
#define IDC_COLOUR_EXT                  1063
#define IDC_RESTORE                     1064
#define IDC_ENABLE_HIGHLIGHT            1065
#define IDC_HEAD_LABEL                  1066
#define IDC_HEAD_COLOUR                 1067
#define IDC_HEAD_STYLE                  1068
#define IDC_HEAD_UNDER                  1069
#define IDC_HEAD_SIZE                   1070
#define IDC_MAIN_LABEL                  1071
#define IDC_MAIN_COLOUR                 1072
#define IDC_MAIN_STYLE                  1073
#define IDC_MAIN_UNDER                  1074
#define IDC_MAIN_SIZE                   1075
#define IDC_COMMENT_LABEL               1076
#define IDC_COMMENT_COLOUR              1077
#define IDC_COMMENT_STYLE               1078
#define IDC_COMMENT_UNDER               1079
#define IDC_COMMENT_SIZE                1080
#define IDC_QUOTE_LABEL                 1081
#define IDC_QUOTE_COLOUR                1082
#define IDC_QUOTE_STYLE                 1083
#define IDC_QUOTE_UNDER                 1084
#define IDC_QUOTE_SIZE                  1085
#define IDC_SUBST_LABEL                 1086
#define IDC_SUBST_COLOUR                1087
#define IDC_SUBST_STYLE                 1088
#define IDC_SUBST_UNDER                 1089
#define IDC_SUBST_SIZE                  1090
#define IDC_PREVIEW                     1091
#define IDC_TABPREVIEW                  1092
#define IDC_FIND                        1093
#define IDC_FIND_ALL                    1094
#define IDC_LOOK_SOURCE                 1095
#define IDC_LOOK_EXTENSIONS             1096
#define IDC_LOOK_DOC_MAIN               1097
#define IDC_LOOK_DOC_CODE               1098
#define IDC_LOOK_DOC_PHRASES            1099
#define IDC_IGNORE_CASE                 1100
#define IDC_FIND_RULE                   1101
#define IDC_FOUND                       1102
#define IDC_RESULTS                     1103
#define IDC_REGEX_HELP                  1104
#define IDC_FIND_NEXT                   1105
#define IDC_FIND_PREVIOUS               1106
#define IDC_REPLACE_WITH                1107
#define IDC_REPLACE_ALL                 1108
#define IDC_REPLACE_FIND                1109
#define IDC_STATIC_OPEN_RECENT          1110
#define IDC_STATIC_ADVICE               1111
#define IDC_STATIC_CREATE_NEW           1112
#define IDC_STATIC_SAMPLE               1113
#define IDC_STATIC_COMMUNITY            1114
#define IDC_STATIC_SUMMON               1115
#define IDC_ADVICE_NEW                  1116
#define IDC_ADVICE_UPGRADE              1117
#define IDC_ADVICE_KEYBOARD             1118
#define IDC_ADVICE_MATERIALS            1119
#define IDC_ADVICE_CREDITS              1120
#define IDC_LINK_INFORM7                1121
#define IDC_LINK_IFDB                   1122
#define IDC_LINK_INTFIC                 1123
#define IDC_LINK_INTFIC_QA              1124
#define IDC_LINK_IFWIKI                 1125
#define IDC_LINK_PLANETIF               1126
#define IDC_LINK_IFCOMP                 1127
#define IDC_LINK_IFDB_SRC               1128
#define IDC_OPEN_0                      1129
#define IDC_OPEN_1                      1130
#define IDC_OPEN_2                      1131
#define IDC_OPEN_3                      1132
#define IDC_OPEN_4                      1133
#define IDC_OPEN_5                      1134
#define IDC_OPEN_6                      1135
#define IDC_OPEN_7                      1136
#define IDC_CREATE_PROJECT              1137
#define IDC_CREATE_EXTENSION            1138
#define IDC_SAMPLE_ONYX                 1139
#define IDC_SAMPLE_DISENCHANTMENT       1140
#define ID_OPEN_EXTENSIONS_LIST         2000
#define ID_NEW_EXTENSIONS_LIST          3000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        285
#define _APS_NEXT_COMMAND_VALUE         285
#define _APS_NEXT_CONTROL_VALUE         1145
#define _APS_NEXT_SYMED_VALUE           100
#endif
#endif
