//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Inform7.rc
//
#define IDR_MANIFEST                    1
#define IDR_MAINFRAME                   100
#define IDR_HTMLMENU                    101
#define IDR_TOOLBAR                     102
#define IDR_TOOLBAR_DISABLED            103
#define IDR_SKEIN                       104
#define IDR_EXTFRAME                    105
#define IDR_FLAT_SELECT                 106
#define IDR_BIG_LOGO                    107
#define IDR_SMALL_LOGO                  108
#define IDD_ABOUTBOX                    150
#define IDD_SETTINGS                    151
#define IDD_SPLASH                      152
#define IDD_SEARCH                      153
#define IDD_NEWPROJECT                  154
#define IDD_SPELLING                    155
#define IDD_PREFERENCES                 156
#define ID_FILE_INSTALL_EXT             200
#define ID_FILE_INSTALL_FOLDER          201
#define ID_FILE_INSTALL_XP              202
#define ID_FILE_NEW_EXT                 203
#define ID_FILE_NEW_XP                  204
#define ID_FILE_IMPORT_SKEIN            205
#define ID_FILE_EXPORT_EXT              206
#define ID_EDIT_DELETE                  207
#define ID_EDIT_SPELLING                208
#define ID_EDIT_SCROLL                  209
#define ID_FORMAT_SHIFT_RIGHT           210
#define ID_FORMAT_SHIFT_LEFT            211
#define ID_FORMAT_COMMENT               212
#define ID_FORMAT_UNCOMMENT             213
#define ID_FORMAT_RENUMBER              214
#define ID_PLAY_GO                      220
#define ID_PLAY_STOP                    221
#define ID_PLAY_TEST                    222
#define ID_PLAY_TEST_EXAMPLES           223
#define ID_PLAY_REFRESH                 224
#define ID_PLAY_LOAD                    225
#define ID_PLAY_REPLAY                  226
#define ID_REPLAY_BLESSED               231
#define ID_REPLAY_SHOW_LAST             232
#define ID_REPLAY_SHOW_LAST_SKEIN       233
#define ID_REPLAY_CHANGED_PREV          234
#define ID_REPLAY_CHANGED_NEXT          235
#define ID_REPLAY_DIFF_PREV             236
#define ID_REPLAY_DIFF_NEXT             237
#define ID_REPLAY_DIFF_NEXT_SKEIN       238
#define ID_RELEASE_GAME                 240
#define ID_RELEASE_TEST                 241
#define ID_RELEASE_MATERIALS            242
#define ID_RELEASE_IFICTION             243
#define ID_WINDOW_TAB_SOURCE            250
#define ID_WINDOW_TAB_RESULTS           251
#define ID_WINDOW_TAB_INDEX             252
#define ID_WINDOW_TAB_SKEIN             253
#define ID_WINDOW_TAB_TRANSCRIPT        254
#define ID_WINDOW_TAB_STORY             255
#define ID_WINDOW_TAB_DOCUMENTATION     256
#define ID_WINDOW_TAB_EXTENSIONS        257
#define ID_WINDOW_TAB_SETTINGS          258
#define ID_WINDOW_SWITCH                259
#define ID_WINDOW_LEFTPANE              260
#define ID_WINDOW_RIGHTPANE             261
#define ID_WINDOW_INDEX_HOME            262
#define ID_WINDOW_INDEX_CONTENTS        263
#define ID_WINDOW_INDEX_ACTIONS         264
#define ID_WINDOW_INDEX_KINDS           265
#define ID_WINDOW_INDEX_PHRASES         266
#define ID_WINDOW_INDEX_RULES           267
#define ID_WINDOW_INDEX_SCENES          268
#define ID_WINDOW_INDEX_WORLD           269
#define ID_HELP_LICENCE                 270
#define ID_HELP_WINDOWS                 271
#define ID_HELP_EXTENSIONS              272
#define ID_HELP_RECIPES                 273
#define ID_APP_PREFS                    274
#define ID_APP_WEBPAGE                  275
#define ID_HEAD_SHOW                    276
#define ID_HEAD_CURRENT                 277
#define ID_HEAD_INCREASE                278
#define ID_HEAD_REDUCE                  279
#define ID_HEAD_ENTIRE                  280
#define ID_HEAD_PREVIOUS                281
#define ID_HEAD_NEXT                    282
#define ID_WINDOW_LIST                  300
#define ID_SKEIN_LABEL                  400
#define ID_SKEIN_TRIM                   401
#define ID_SKEIN_PLAY                   402
#define ID_SKEIN_EDIT                   403
#define ID_SKEIN_ADD_LABEL              404
#define ID_SKEIN_EDIT_LABEL             405
#define ID_SKEIN_TRANSCRIPT             406
#define ID_SKEIN_LOCK                   407
#define ID_SKEIN_UNLOCK                 408
#define ID_SKEIN_LOCK_THREAD            409
#define ID_SKEIN_UNLOCK_THREAD          410
#define ID_SKEIN_NEW_THREAD             411
#define ID_SKEIN_INSERT_KNOT            412
#define ID_SKEIN_DELETE                 413
#define ID_SKEIN_DELETE_BELOW           414
#define ID_SKEIN_DELETE_THREAD          415
#define ID_SKEIN_SAVE_TRANSCRIPT        416
#define ID_SKEIN_PLAY_ALL               417
#define ID_TRANSCRIPT_BLESS_ALL         420
#define ID_SEARCH_SOURCE                450
#define ID_SEARCH_DOCS                  451
#define ID_NAVIGATE_BACK                500
#define ID_NAVIGATE_FORE                501
#define ID_MENU_PROPERTIES              550
#define IDC_CREDITS                     1000
#define IDC_OUTPUT_Z8                   1002
#define IDC_OUTPUT_GLULX                1003
#define IDC_BLORB                       1004
#define IDC_PREDICTABLE                 1005
#define IDC_PROGRESS                    1010
#define IDC_LOGO                        1011
#define IDC_TITLE                       1012
#define IDC_COPYRIGHT                   1013
#define IDC_NEW_PROJECT                 1014
#define IDC_OPEN_PROJECT                1015
#define IDC_INTRO                       1016
#define IDC_SEARCH_SOURCE               1017
#define IDC_SEARCH_DOCS                 1018
#define IDC_SEARCH_RESULTS              1019
#define IDC_REOPEN_LAST                 1020
#define IDC_VERSION                     1021
#define IDC_DIR                         1022
#define IDC_DIRPOPUP                    1023
#define IDC_NAME                        1024
#define IDC_AUTHOR                      1025
#define IDC_TRANSCRIPT_EDIT             1026
#define IDC_DIR_TEXT                    1027
#define IDC_NAME_TEXT                   1028
#define IDC_BADWORD                     1029
#define IDC_SUGGESTIONS                 1030
#define IDC_ADD_DICTIONARY              1031
#define IDC_IGNORE                      1032
#define IDC_REPLACE                     1033
#define IDC_TABSIZE                     1034
#define IDC_CLEANFILES                  1035
#define IDC_CLEANINDEX                  1036
#define IDC_I6DEBUGGING                 1037
#define IDC_LANGUAGE                    1038
#define IDC_STARTLAST                   1039
#define IDC_GLULX                       1040
#define IDC_INDENT                      1041
#define IDC_AUTO_INDENT                 1042
#define IDC_AUTO_NUMBER                 1043
#define IDC_FONT                        1044
#define IDC_FONTSIZE                    1045
#define IDC_FIXEDFONT                   1046
#define IDC_ELASTIC_TABS                1047
#define IDC_STORY_BOX                   1048
#define IDC_RANDOM_BOX                  1049
#define IDC_EXAMPLE_DROP                1050
#define ID_OPEN_EXTENSIONS_LIST         2000
#define ID_NEW_EXTENSIONS_LIST          3000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        283
#define _APS_NEXT_COMMAND_VALUE         283
#define _APS_NEXT_CONTROL_VALUE         1051
#define _APS_NEXT_SYMED_VALUE           100
#endif
#endif
